<?php
include_once 'admin-class.php';
//$retailer="";
//$comm=0.60;

//$session=$_POST['session'];
//$tran="1000438608669";
session_start();
$fields_string="";
//$alternate=$_POST['alternate'];
$user_name=$_SESSION['user_names'];
//echo ($customerNo);
$challan_no=$_POST['challan_no'];
$order_id=$_POST['order_id'];
$quantity=$_POST['qty2'];
$material_id=$_POST['material_id1'];
$uom=$_POST['uom2'];
$remark=urlencode($_POST['remark2']);
$remark=str_replace("+","%20",$remark);
$lr_no=$_POST['lr_no'];
$dates=$_POST['actual_date'];
$transport_name=urlencode($_POST['transport_name']);
$transport_name=str_replace("+","%20",$transport_name);
$vihicle_type=urlencode($_POST['vihicle_type']);
$vihicle_type=str_replace("+","%20",$vihicle_type);
$driver_name=urlencode($_POST['driver_name']);
$driver_name=str_replace("+","%20",$driver_name);
$driver_mob=$_POST['driver_mob'];
$vehicle_num=urlencode($_POST['vehicle_num']);
$vehicle_num=str_replace("+","%20",$vehicle_num);
$user_type="BMSoperational";
$order_items_id=$_POST['order_items_id'];
//ResagitB2B/updateStockTransferDetails/"+challanNo+"/"+orderID+"/"+quantityCount+"/"+remarkCount.replaceAll("\\s", "%20")+"/"+materialID+"/"+userNumber+"/"+type+"/"+lrNumber+"/"+vehicleTypeName.replaceAll("\\s", "%20")+"/"+vehicleNo.replaceAll("\\s", "%20")+"/"+driver.replaceAll("\\s", "%20")+"/"+transport.replaceAll("\\s", "%20")+"/"+date+"/"+driverNo;
$url="http://".$ip."/updateStockTransferDetails/$challan_no/$order_id/$quantity/$remark/$material_id/$user_name/$user_type/$lr_no/$vihicle_type/$vehicle_num/$driver_name/$transport_name/$dates/$driver_mob/$order_items_id";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
curl_setopt($ch, CURLOPT_MAXREDIRS, 3);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
$data = curl_exec($ch);
echo $data;